version: '3'

services:

  web:
    build: ./docker-file/web/
    ports:
      - 8080:80
    volumes:
      - ./volumes/web/html:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:9.3
    ports:
      - 5433:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
